#!/bin/bash

WEB_SESSION=librewolf

cd ~/Bookmarks
SEARCH=$(find * -type f | wofi -d -G)

if [ -f '${SEARCH}' ]; then
  echo $SEARCH
  swaymsg exec -- $WEB_SESSION $(cat $SEARCH)
elif [ "$SEARCH" ]; then
  swaymsg exec -- $WEB_SESSION $(cat "$SEARCH")
fi
